# frontend/Dockerfile

# Этап сборки фронтенда
FROM node:16 as build

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходный код и выполняем сборку
COPY . .
RUN npm run build

# Этап для Nginx
FROM nginx:alpine

# Копируем собранные файлы фронтенда в директорию Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Порт для Nginx
EXPOSE 80

# Запуск Nginx
CMD ["nginx", "-g", "daemon off;"]

