version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beauty_db

  backend:
    build: ./backend
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beauty_db
      POSTGRES_HOST: db
      NODE_ENV: production
    depends_on:
      - db

  nginx:
    build: ./frontend  # Используем Dockerfile из директории frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
