version: '3.8'

networks:
  beauty-network:
    driver: bridge

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beauty_db
    networks:
      - beauty-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beauty_db
      POSTGRES_HOST: db
      NODE_ENV: production
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - beauty-network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - beauty-network
    command: ["nginx", "-g", "daemon off;"]

volumes:
  postgres_data:
