version: '3'

networks:
  beauty-network:
    driver: bridge

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beauty_db
    networks:
      - beauty-network

  backend:
    build: ./backend
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beauty_db
      POSTGRES_HOST: db
      NODE_ENV: production
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - beauty-network
    # command: ["sh", "-c", "./wait-for.sh db 5432 -- npm run start"]  # Явно используем 'sh' для запуска wait-for.sh

  frontend:
    build:
      context: ./frontend
      target: build
    image: frontend:latest
    networks:
      - beauty-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - beauty-network
    command: ["sh", "-c", "./wait-for.sh frontend 80 -- nginx -g 'daemon off;'"]  # Явно используем 'sh' для запуска wait-for.sh

volumes:
  postgres_data:
